AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
