development:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: bingo_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: bingo_production
