development: &default
  adapter: postgresql
  encoding: unicode
  database: bingo_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>
  template: 'template0'

test:
  <<: *default
  database: bingo_test
